// Array of Roman Empire fun facts
const romanFacts = [
    "The Roman Empire was one of the largest empires in history, spanning three continents.",
    "Romans used a system of underfloor heating called 'hypocaust' in their buildings.",
    "Julius Caesar was assassinated in 44 BCE, leading to the rise of the Roman Empire.",
    "The Colosseum in Rome could hold up to 80,000 spectators for events.",
    "Latin, the language of the Romans, has influenced many modern languages, including English, French, Spanish, and Italian.",
    "The Roman alphabet is still used today and is the basis for many modern writing systems.",
    "The Roman aqueducts were engineering marvels that transported water over long distances to supply cities.",
    // Additional facts
    "The Roman Forum was the heart of political, commercial, and judicial life in ancient Rome.",
    "Gladiators were usually slaves or prisoners of war, and their fights were a form of entertainment.",
    "Roman emperors were often deified after death, with temples built in their honor.",
    "The Roman military was one of the most powerful and disciplined in the ancient world.",
    "The Roman legions were divided into smaller units called centuries.",
    "The Roman calendar was based on the cycles of the moon, which led to occasional adjustments.",
    "Romans celebrated a festival called Saturnalia, a time of feasting, gift-giving, and revelry.",
    "The city of Pompeii was preserved by the volcanic ash from the eruption of Mount Vesuvius in 79 CE.",
    "The famous saying 'Veni, Vidi, Vici' (I came, I saw, I conquered) is attributed to Julius Caesar.",
    "Roman architecture, with features like arches and domes, has influenced buildings for centuries.",
    "The Roman Senate was a powerful political institution that advised magistrates and passed laws.",
    "Roman law, known as the Twelve Tables, formed the basis of modern legal systems.",
    "The Roman Pantheon is a well-preserved temple in Rome dedicated to all the gods of ancient Rome.",
    "The Roman road network, known as the Viae, facilitated communication and trade across the empire.",
    "Cleopatra, the last Pharaoh of Egypt, had relationships with both Julius Caesar and Mark Antony.",
    "Roman emperors were often depicted in statues and artwork to convey power and authority.",
    "Roman citizens enjoyed a wide range of public entertainment, including chariot races and theatrical performances.",
    "Roman gladiators had different fighting styles, and some were trained to use specific weapons.",
    "The Roman Empire fell in 476 CE, marking the end of ancient Rome.",
    "Roman engineers were skilled in constructing bridges, aqueducts, and siege engines.",
    "The Roman Toga was a distinctive garment worn by citizens on formal occasions.",
    "Romans made significant advances in medicine, including the development of surgical instruments.",
    "Roman mythology influenced art, literature, and culture throughout the empire.",
    "The Arch of Constantine in Rome commemorates the victory of Constantine the Great.",
    "Roman emperors often held elaborate triumphal processions after military victories.",
    "The Roman navy, known as the Classis, played a crucial role in protecting the empire's borders.",
    "Romans used a complex system of numerals, with symbols like I, V, X, L, C, D, and M.",
    "The Roman toga was a symbol of citizenship and was worn by adult male citizens.",
    "The Roman poet Virgil wrote the epic poem 'The Aeneid,' which tells the story of the Trojan hero Aeneas.",
    "Roman bathhouses, or thermae, were social centers with hot and cold baths.",
    "Roman gladiatorial contests were often sponsored by wealthy individuals seeking public favor.",
    "Romans built extensive fortifications, such as Hadrian's Wall in Britain, to defend the empire's borders.",
    "The Roman Empire had a complex system of government, including the Senate, magistrates, and emperors.",
    "Roman emperors commissioned grand buildings, monuments, and statues to showcase their achievements.",
    "Romans enjoyed a variety of foods, including bread, olives, wine, and exotic imports.",
    "The Roman poet Ovid wrote the 'Metamorphoses,' a collection of myths and legends.",
    "Roman engineers used the arch and the dome in architecture, creating enduring structures.",
    "The Roman legal concept of 'innocent until proven guilty' has influenced modern legal systems.",
    "Roman gladiators had distinctive armor and weapons, and some became popular heroes.",
    "Romans built extensive networks of roads to connect the far reaches of the empire.",
    "The Roman Empire reached its height under Emperor Trajan in the 2nd century CE.",
    "The Roman general Scipio Africanus defeated Hannibal in the Second Punic War.",
    "Roman citizens were entitled to certain rights, including the right to vote and legal protection.",
    "The Roman poet Horace coined the phrase 'carpe diem' (seize the day).",
    "Roman emperors often built triumphal arches to commemorate military victories.",
    "Romans used the Roman numerals for various purposes, including numbering the chapters of books.",
    "The Roman goddess Venus was associated with love, beauty, and fertility.",
    "The Roman philosopher Seneca wrote essays on ethics, stoicism, and the nature of life.",
    "Roman engineers developed sophisticated techniques for constructing large structures.",
    "The Roman historian Livy chronicled the history of Rome in his monumental work 'Ab Urbe Condita.'",
    "Romans enjoyed public spectacles, including chariot races at the Circus Maximus.",
    "The Roman Empire faced internal strife and external threats, contributing to its decline.",
    "Roman emperors often had elaborate titles, such as 'Augustus' and 'Caesar.'",
    "Romans made significant contributions to art, literature, philosophy, and science.",
    "The Roman military used a formation called the 'Testudo' (tortoise) for protection during sieges.",
    "Roman citizens were divided into social classes, with the patricians and plebeians holding different privileges.",
    "The Roman poet Juvenal coined the phrase 'panem et circenses' (bread and circuses) to describe the distractions provided to the Roman populace.",
    "Romans had a complex system of religious beliefs, with numerous gods and goddesses.",
    "The Roman Empire had a vast network of spies and informants to maintain control.",
    "Roman emperors often built monumental structures, such as the Roman Forum and the Colosseum.",
    "Romans developed advanced techniques in construction, including the use of concrete.",
    "The Roman Republic transitioned into the Roman Empire with the rise of Augustus.",
    "Roman engineers constructed monumental arches, such as the Arch of Titus and the Arch of Septimius Severus.",
    "Romans used a legal concept called 'jus civile' to govern relations among citizens.",
    "The Roman god Mars was associated with war and was highly revered by the military.",
    "Roman gladiators trained in special schools called 'ludi,' where they learned combat techniques.",
    "Romans celebrated the festival of Lupercalia, which involved rituals for fertility and purification.",
    "The Roman poet Catullus is known for his passionate and sometimes humorous love poems.",
    "Roman emperors built impressive villas, such as Hadrian's Villa in Tivoli.",
    "Romans had a system of public welfare called the 'annona,' which provided free grain to citizens.",
    "The Roman Empire had a complex system of provinces and territories governed by appointed officials.",
    "Roman emperors often had coins minted to commemorate their reigns and achievements.",
    "Romans had a strong tradition of public speaking, with famous orators like Cicero.",
    "The Roman playwright Plautus wrote comedies that are still performed today.",
    "Romans had a strong belief in the importance of family and ancestral spirits.",
    "The Roman philosopher Epictetus emphasized the importance of self-control and rationality.",
    "Roman engineers developed innovative techniques for constructing large buildings, such as the Pantheon.",
    "Romans used a system of slavery to support their economy and workforce.",
    "The Roman Empire had a vast network of roads, allowing for efficient travel and communication.",
    "Roman emperors often adopted successors to ensure the continuity of power.",
    "Romans enjoyed a wide range of entertainment, including theatrical performances and chariot races.",
    "The Roman Empire faced challenges from various barbarian invasions, including the Visigoths and Vandals.",
    "Roman gladiators had specific roles, such as 'retiarius' (net-fighter) and 'secutor' (pursuer).",
    "Romans constructed elaborate bathhouses, with facilities for hot and cold baths.",
    "The Roman Senate played a crucial role in advising magistrates and shaping government policy.",
    "Roman engineers constructed impressive structures, such as the Pont du Gard aqueduct in France.",
    "Romans used a legal system called 'jus gentium' to govern relations with foreigners.",
    "The Roman Empire had a thriving trade network, connecting distant regions through commerce.",
    "Roman emperors often built triumphal columns, such as Trajan's Column in Rome.",
    "Romans were skilled in the art of mosaic, creating intricate designs for floors and walls.",
    "The Roman god Neptune was associated with the sea and maritime activities.",
    "Roman emperors sponsored public games and festivals to maintain popularity.",
    "Romans made significant contributions to mathematics, including the development of Roman numerals.",
    "The Roman poet Martial wrote humorous and satirical epigrams that commented on daily life.",
    "Roman engineers constructed elaborate systems of sewers and drains to manage waste.",
    "Romans celebrated the festival of Bacchanalia, which involved revelry and the worship of Bacchus.",
    "The Roman Empire had a network of spies and informants to gather information and maintain control.",
    "Roman gladiators were often depicted in mosaics, paintings, and sculptures.",
    "Romans had a system of social patronage, with patrons providing support and protection to clients.",
    "The Roman military used a formation called the 'Testudo' (tortoise) for protection during sieges.",
    "Roman citizens enjoyed a wide range of entertainment, including chariot races and gladiator contests.",
    "Romans had a strong tradition of public baths, with facilities for socializing and exercise.",
    "The Roman goddess Venus was associated with love, beauty, and fertility.",
    "Roman emperors often had elaborate titles, such as 'Augustus' and 'Caesar.'",
    "Romans made significant contributions to art, literature, philosophy, and science.",
    "The Roman military used a formation called the 'Testudo' (tortoise) for protection during sieges.",
    "Roman citizens were divided into social classes, with the patricians and plebeians holding different privileges.",
    "The Roman poet Juvenal coined the phrase 'panem et circenses' (bread and circuses) to describe the distractions provided to the Roman populace.",
    "Romans had a complex system of religious beliefs, with numerous gods and goddesses.",
    "The Roman Empire had a vast network of spies and informants to maintain control.",
    "Roman emperors often built monumental structures, such as the Roman Forum and the Colosseum.",
    "Romans developed advanced techniques in construction, including the use of concrete.",
    "The Roman Republic transitioned into the Roman Empire with the rise of Augustus.",
    "Roman engineers constructed monumental arches, such as the Arch of Titus and the Arch of Septimius Severus.",
    "Romans used a legal concept called 'jus civile' to govern relations among citizens.",
    "The Roman god Mars was associated with war and was highly revered by the military.",
    "Roman gladiators trained in special schools called 'ludi,' where they learned combat techniques.",
    "Romans celebrated the festival of Lupercalia, which involved rituals for fertility and purification.",
    "The Roman poet Catullus is known for his passionate and sometimes humorous love poems.",
    "Roman emperors built impressive villas, such as Hadrian's Villa in Tivoli.",
    "Romans had a system of public welfare called the 'annona,' which provided free grain to citizens.",
    "The Roman Empire had a complex system of provinces and territories governed by appointed officials.",
    "Roman emperors often had coins minted to commemorate their reigns and achievements.",
    "Romans had a strong tradition of public speaking, with famous orators like Cicero.",
    "The Roman playwright Plautus wrote comedies that are still performed today.",
    "Romans had a strong belief in the importance of family and ancestral spirits.",
    "The Roman philosopher Epictetus emphasized the importance of self-control and rationality.",
    "Roman engineers developed innovative techniques for constructing large buildings, such as the Pantheon.",
    "Romans used a system of slavery to support their economy and workforce.",
    "The Roman Empire had a vast network of roads, allowing for efficient travel and communication.",
    "Roman emperors often adopted successors to ensure the continuity of power.",
    "Romans enjoyed a wide range of entertainment, including theatrical performances and chariot races.",
    "The Roman Empire faced challenges from various barbarian invasions, including the Visigoths and Vandals.",
    "Roman gladiators had specific roles, such as 'retiarius' (net-fighter) and 'secutor' (pursuer).",
    "Romans constructed elaborate bathhouses, with facilities for hot and cold baths.",
    "The Roman Senate played a crucial role in advising magistrates and shaping government policy.",
    "Roman engineers constructed impressive structures, such as the Pont du Gard aqueduct in France.",
    "Romans used a legal system called 'jus gentium' to govern relations with foreigners.",
    "The Roman Empire had a thriving trade network, connecting distant regions through commerce.",
    "Roman emperors often built triumphal columns, such as Trajan's Column in Rome.",
    "Romans were skilled in the art of mosaic, creating intricate designs for floors and walls.",
    "The Roman god Neptune was associated with the sea and maritime activities."
];

// Idea: instead of random, set the list to shuffle on page refresh then just go through the list in order?
// Function to shuffle the array
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Function to get a random fun fact
function getRandomFact() {
    shuffleArray(romanFacts);
    const fact = romanFacts[0];
    document.getElementById("funFact").innerText = fact;
}
